import { ApartmentIcon } from "../assets/svg/svg";

export const data = [
  {
    img: "/cards/news/Rectangle 18.png",
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "2 روز پیش",
    price: "۲۳۲ میلیارد",
    priceByEachMeter: " متری ۶۰ تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
      "/cards/news/Rectangle 17.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۵۸ میلیارد",
    priceByEachMeter: " متری 20 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 19.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 18.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: false,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۲۳۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: false,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 18.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۱۲۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 18.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  
];
