import { ApartmentIcon } from "../assets/svg/svg";

export const data = [
  {
    img: "/cards/news/Rectangle 18.png",
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "2 روز پیش",
    price: "۲۳۲ میلیارد",
    priceByEachMeter: " متری ۶۰ تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
      "/cards/news/Rectangle 17.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۵۸ میلیارد",
    priceByEachMeter: " متری 20 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 19.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 18.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: false,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۲۳۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: false,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 18.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۱۲۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/cards/news/Rectangle 18.png",
      "/cards/news/Rectangle 17.png",
      "/cards/news/Rectangle 19.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  
];


export const woodData = [
  {
    title: "فروش ویلای استخردار ساحلی در متل قو",
    time: "2 روز پیش",
    price: "89 میلیارد",
    priceByEachMeter: " متری ۶۰ تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/beach/18380580 1.png",
      "/public/cards/beach/98 1.png",
      "/public/cards/beach/Neighbourhood-1-Baan-Banyan-Pool-and-Tropical-Jungle-view 1.png",
      "/public/cards/beach/98 1.png",

    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  {
    title: "فروش ویلای استخردار ساحلی در متل قو",
    time: "1 روز پیش",
    price: "100 میلیارد",
    priceByEachMeter: " متری 20 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/beach/98 1.png",
      "/public/cards/beach/18380580 1.png",
      "/public/cards/beach/Neighbourhood-1-Baan-Banyan-Pool-and-Tropical-Jungle-view 1.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: false,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "45 میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: false,
    logo: ApartmentIcon,
    media: [
      "/public/cards/beach/Neighbourhood-1-Baan-Banyan-Pool-and-Tropical-Jungle-view 1.png",
      "/public/cards/beach/98 1.png",
      "/public/cards/beach/18380580 1.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },  {
    title: "فروش ویلای استخردار ساحلی در متل قو",
    time: "1 روز پیش",
    price: "۱۲۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/beach/Neighbourhood-1-Baan-Banyan-Pool-and-Tropical-Jungle-view 1.png",
      "/public/cards/beach/18380580 1.png",
      "/public/cards/beach/98 1.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  
];


export const beachData = [
  {
    title: "فروش ویلای استخردار ساحلی در متل قو",
    time: "2 روز پیش",
    price: "89 میلیارد",
    priceByEachMeter: " متری ۶۰ تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/woods/Large-hotelimages-royal-garden-villas-275980-1 1.png",
      "/public/cards/woods/ocean1 1.png",
      "/public/cards/woods/oceanview-luxury-villa-phuket 1.png",

    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  {
    title: "فروش ویلای استخردار ساحلی در متل قو",
    time: "1 روز پیش",
    price: "100 میلیارد",
    priceByEachMeter: " متری 20 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/woods/oceanview-luxury-villa-phuket 1.png",

      "/public/cards/woods/Large-hotelimages-royal-garden-villas-275980-1 1.png",
      "/public/cards/woods/oceanview-luxury-villa-phuket 1.png",
      "/public/cards/woods/ocean1 1.png",

    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: false,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "45 میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: false,
    logo: ApartmentIcon,
    media: [
      "/public/cards/woods/oceanview-luxury-villa-phuket 1.png",

      "/public/cards/woods/ocean1 1.png",

      "/public/cards/woods/Large-hotelimages-royal-garden-villas-275980-1 1.png",
      "/public/cards/woods/oceanview-luxury-villa-phuket 1.png",

    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },  {
    title: "فروش آپارتمان ساحلی قواره دوم دریا در آویدر نوشهر",
    time: "1 روز پیش",
    price: "۱۲۲ میلیارد",
    priceByEachMeter: " متری 40 تومان",
    informations: ["102 متر", "3 خوابه ", "2 طبقه", "نوساز"],
    special: true,
    logo: ApartmentIcon,
    media: [
      "/public/cards/woods/ocean1 1.png",
      "/public/cards/beach/18380580 1.png",
      "/public/cards/beach/98 1.png",
    ],
    profile: "/cards/profile/prof3.png",
    userName: "پویا حدادی",
    experience: "۱۰ سال تجربه",
    Presell: true,
  },
  
];